services:
  - type: web
    name: jobly-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_BASE_URL
        value: https://jobly-backend-zp0b.onrender.com 