services:
  - type: web
    name: jobly-frontend
    buildCommand: cd jobly-frontend && npm install && npm run build
    staticPublishPath: jobly-frontend/build
    envVars:
      - key: REACT_APP_BASE_URL
        value: https://jobly-backend-zp0b.onrender.com 