static_sites:
  - name: jobly-frontend
    buildCommand: cd jobly-frontend && npm install && export NODE_OPTIONS=--openssl-legacy-provider && GENERATE_SOURCEMAP=false npm run build
    publishPath: build
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_BASE_URL
        fromService:
          name: jobly-backend
          type: web
          property: url
      - key: NODE_OPTIONS
        value: --openssl-legacy-provider
    healthCheckPath: /
    autoDeploy: true 